algorithm:
  clip_range: 0.2
  demand_lambda: 1.0
  entropy_lambda: 0.010071090711145904
  feasibility_lambda: 0.2828168389831236 #VP: 0.2828168389831236 #FR: 0.19541109874275892
  gae_lambda: 0.95
  gamma: 0.99
  max_grad_norm: 0.5
  mini_batch_size: 0.5
  primal_dual: false
  ppo_epochs: 5
  stability_lambda: 1.0
  tau: 0.005
  type: sac # ppo #sac
  vf_lambda: 0.5
env:
  CI_target: 1.25
  LCG_target: 0.95
  TEU: 1000 # 20000, 1000
  VCG_target: 1.05
  bays: 10 #10, 20
  blocks: 2
  capacity:
  - 50 # 50, 500
  cargo_classes: 6
  customer_classes: 2
  cv_demand: 0.5
  decks: 2
  demand_uncertainty: true
  env_name: mpp #block_mpp #mpp
  episode_order: standard
  generalization: false
  hatch_overstowage_costs: 0.333333
  hatch_overstowage_mask: false
  block_stowage_mask: false
  iid_demand: true
  limit_revenue: true
  long_crane_costs: 0.5
  normalize_obs: true
  perturbation: 0.2
  ports: 4
  seed: 42
  spot_percentage: 0.3
  stability_difference: 0.1
  utilization_rate_initial_demand: 1.1 #0.7, 0.9, 1.1., 1.3, 1.5
  weight_classes: 3
model:
  batch_size: 64
  critic_temperature: 1.0
  decoder_type: attention # mlp, attention
  dropout_rate: 0.008972135903337364
  dyn_embed: self_attention # ffn, self_attention
  embed_dim: 128
  encoder_type: attention # mlp, attention
  hidden_dim: 512 # 128
  init_dim: 8
  logger: wandb
  lr_end_factor: 0.5
  normalization: layer
  num_decoder_layers: 4 # 3
  num_encoder_layers: 3
  num_heads: 8
  phase: train
  scale_max: 1.931286785557626 #9.459951968688712 # 1.931286785557626 # 0.25
  tanh_clipping: 0
  tanh_squashing: false
  temperature: 0.11243639449117128
testing:
  feasibility_recovery: false
  folder: 'sac-pd' #'sac-ws+pc' #'SA_AM'
  num_episodes: 30
  path: results/trained_models/navigating_uncertainty
  # results/trained_models/AI2STOW_JOURNAL_VERSION
  # results/trained_models/navigating_uncertainty
  # results/trained_models/AI2STOW
training:
  lr: 0.00014690714579803494
  pd_lr: 0.000034690714579803494
  optimizer: Adam
  projection_kwargs:
    alpha: 0.01 #0.050 #0.01 #0.00987804770039214
    delta: 0.01 #0.050 #0.01 #0.023908679032053855
    max_iter: 300 #300 #273
    n_action: 20 #20 #80
    n_constraints: 25 #25 #85
    scale: 0.00025463040788043916 #0.00015463040788043916
    slack_penalty: 10000 #1000
    use_early_stopping: true
  projection_type: None
  # None, weighted_scaling_policy_clipping, linear_violation, linear_violation_policy_clipping, convex_program, convex_program_policy_clipping
  test_data_size: 5000
  train_data_size: 7200000
  val_data_size: 5000
  validation_freq: 0.2
  validation_patience: 2
wandb_version: 1